### ISSUE TITLE
Consider allowing numeric columns in step_dummy()

### ISSUE THREAD

**Issue by kevinykuo** [topepo/recipes#100]
e.g.
```
df <- data.frame(target = rnorm(10), cat = sample(1:3, 10, replace = TRUE))
recipe(target ~ cat, data = df) %>%
  step_dummy(cat) %>%
  prep(data = df)
# Error: The following variables are not factor vectors: `cat` 
```
Use case is that the variable may be encoded as numeric in the input dataset. This way users wouldn't have to call `as.character()` outside the recipe. Or maybe there's a `step` for this I'm missing?

**Comment by topepo** [comment]
If it were character, there is `step_string2factor` but not `step_num2factor`. I would rather add that than relax the test for type.

**Comment by topepo** [comment]
I've added [`step_num2factor`](https://github.com/topepo/recipes/blob/master/R/num2factor.R) if that helps.

**Comment by kevinykuo** [comment]
Thanks!
