### ISSUE TITLE
Feature Request: step_log1p

### ISSUE THREAD

**Issue by mdancho84** [topepo/recipes#124]
It's very common to deal with skewed data that begins at zero and extends in the positive direction. In these circumstances, a log transformation fails due to `Inf` that need to be dealt with. However, a log plus 1 transformation often yields a better correlation than other transformations that are resistant to zeros such as sqrt. A new step that incorporates the base R function, `log1p()`, is requested: `step_log1p()`.

**Comment by topepo** [comment]
I'll add an `offset` argument to `step_log`. You'd be better off estimating a transformation using the Yeo-Johnson transformation though.

**Comment by mdancho84** [comment]
Yes Yeo Johnson is where we end up due to optimization and how it deals with negative and zeros. Thanks for adding!
