### ISSUE TITLE
Install R 3.4.3 on windows 10 through SCCM, 

### ISSUE THREAD

**Issue by kriksh** [topepo/recipes#134]
Hello,

I'm Trying to install R 3.4.3 on windows 10 through SCCM(system context)
, while installing it I'm getting " Internal error: Failed to expandshell folder constant "userdocs"
any answers please let me know thanks!

**Comment by topepo** [comment]
I've never seen that not do I know what SCCM is. Can you give the results of `sessionInfo()` and the code that you used to install?
