### ISSUE TITLE
Safe to remove recipe$template?

### ISSUE THREAD

**Issue by michaellevy** [topepo/recipes#138]
Hi Max, when a recipe is trained on a large dataset, we might not want to carry around a copy of it in the `template` slot. It seems like it's at least sometimes safe to delete it (code below seems to work fine). Do you have any guidance on when it might not be safe to? Thanks.

```r
suppressPackageStartupMessages({library(recipes); library(caret)})

data(segmentationData)
seg_train <- segmentationData %>% 
  filter(Case == "Train") %>% 
  select(-Case, -Cell)
seg_test  <- segmentationData %>% 
  filter(Case == "Test")  %>% 
  select(-Case, -Cell)

rec_obj <- 
  recipe(Class ~ ., data = seg_train) %>%
  step_center(all_predictors()) %>%
  step_scale(all_predictors()) %>%
  prep(training = seg_train)
rec_obj$template <- NULL
bake(rec_obj, seg_train)
bake(rec_obj, seg_test)
```

**Comment by topepo** [comment]
I think that it would be fine. Also, you could give `recipe` the first few lines via `head`; the template is only used to get variable information (e.g. character, numeric, etc).

**Comment by michaellevy** [comment]
Thanks. Would you like a PR for just keeping the head of the data in the template, or would you rather users deal with this elsewhere?

**Comment by michaellevy** [comment]
Sounds good. Thanks.
