### ISSUE TITLE
Reference level for bin2factor

### ISSUE THREAD

**Issue by michaellevy** [topepo/recipes#141]
Currently the level that replaces "1"s becomes the reference level. Is there a reason for that? My use case for this step is for outcomes, and there we definitely want whatever replaces "0" to be the reference level. If it were a predictor, I think you'd want the same... if you were getting a coefficient for it, you'd want the the change from no -> yes, but currently you'd get the opposite.

**Comment by michaellevy** [comment]
Great. I'd like to work on this if you don't mind. I would think to do this by making the `levels` argument a named vector to specify which level replaces which integer and the first position becomes the reference level. Could do:

1. `levels = c("0" = "no", "1" = "yes")`, but that's awkward and inconsistent with `dplyr::rename` where `rename(newx = x)` means "replace x with newx". 
2. `levels = c(no = 0, yes = 1)` would require "if it's a named vector, the names are the levels, otherwise the entries are the levels", which is awkward.
3. Add an argument, maybe `ref_level`, that's one of the entries in `levels` and sets the reference.

Do you like any of those @topepo ?

**Comment by topepo** [comment]
> I'd like to work on this if you don't mind.

I was hoping that you would say that. 😃

I would add some sort of logical that is something like `first_lev` (or better named). That way, the step can process a lot of columns that might have different levels.

**Comment by topepo** [comment]
closed by #142
