### ISSUE TITLE
Function Reference Ordering

### ISSUE THREAD

**Issue by mdancho84** [topepo/recipes#146]
Hey Max,
Great meeting you in NYC. Here's more of a suggestion to help with being able to quickly pick out which options are available for a given task. I suggest that the [Step Functions in the Function Reference](https://topepo.github.io/recipes/reference/index.html#section-step-functions) be ordered in sub-sections by your [7 Preprocessing Steps](https://topepo.github.io/recipes/articles/Ordering.html). This will make it easier to pick out which steps are available at which step in your suggested workflow. 
-Matt

**Comment by topepo** [comment]
Good point. Check this out and make edits it you see fit

**Comment by mdancho84** [comment]
That's awesome!!! If you can push quickly, I can work it into our Data Science For Business Course!

**Comment by topepo** [comment]
I'll try. `pkgdown` doesn't make it easy to refresh the docs without contaminating it with the devel version.

**Comment by mdancho84** [comment]
Max, great work!! I just checked it out, and the new reference layout looks great! https://topepo.github.io/recipes/reference/index.html 

I'll re-record the part that goes over the `step_*` functions. Again, nice work!

**Comment by topepo** [comment]
It's [live now](https://topepo.github.io/recipes/reference/index.html)

**Comment by mdancho84** [comment]
Hey Max,

Just an FYI, I've integrated the recipes package into my [Data Science For Business course](https://university.business-science.io/p/hr201-using-machine-learning-h2o-lime-to-predict-employee-turnover). From an educator's perspective, the new layout makes a world of a difference. Here's an example from one of the lectures on centering and scaling. It makes it so easy to point learners to the right section in your documentation. 

![image](https://user-images.githubusercontent.com/13734662/39442284-a4642360-4c7e-11e8-8eef-df816b2e5cfd.png)
