### ISSUE TITLE
Adding a signed_log

### ISSUE THREAD

**Issue by EdwinTh** [topepo/recipes#148]
I personally find this very helpful for taking a log on variables that contain negative values. It is defined as 

    ifelse(abs(x) < 1, 0, sign(x) * log(abs(x))

I have the code already for this, as it is in the [eRum presentation](https://github.com/EdwinTh/recipe_for_recipes/blob/master/eRum.Rmd). I could either do a PR for a new step, or I could modify the existing `step_log`. My preference would be the former, but please tell me what is yours.

**Comment by artichaud1** [comment]
Sorry for hijacking, but I wonder: is the fact that there isn't a general `step_func` on purpose ? (esp. for cases like this one where the `prep` function would actually do nothing). If so I would be curious to know the rationale.

**Comment by topepo** [comment]
That might be a bit of a nightmare to support since there would probably be a lot of things that could go wrong. I will be implementing a few `dplyr` verbs (`filter` and `mutate`) that can be used in steps. would that cover what you want to do?

**Comment by topepo** [comment]
> I could modify the existing `step_log`

That is my preference.

**Comment by EdwinTh** [comment]
Ok will do
