### ISSUE TITLE
(generalized) linear embedding methods for categorical predictors

### ISSUE THREAD

**Issue by topepo** [topepo/recipes#151]
Based on comments from topepo/FES#4 and topepo/FES#8, add recipes for taking the estimates of the coefficients in a `glm` or `stan_glmer` and use these to encode. 

Random thoughts:

* new levels would be encoded by the average of the estimates (at least that's how it would work in the Bayesian approach)
* use a `glm` and base `family` off of the outcome type (factor and numeric outcomes to start with). Not sure what to do about multinomial outcomes for now. 
* Fit a model for each predictor separately; including them all would raise the likelihood of linear dependencies and `NA` coefficient values. 
* maybe start a `stanrecipes` package to isolate that dependency
* `keras::layer_embedding` could be used to a [similar encoding](https://arxiv.org/abs/1604.06737) and would probably lead to `tfrecipes`. We would have to convert the model output to `raw` to preserve the results after the session ends (unless we can get the coefficients and do it ourselves)

**Comment by topepo** [comment]
The the `topepo/embed` package and, specifically, topepo/embed#2. @alexpghayes would "be happy to make a PR" 😃

**Comment by alexpghayes** [comment]
It's on the way! It just turns out I am very bad at estimating how long it will take to get things done.

**Comment by topepo** [comment]
You'll fit right in 😀

There's no hurry.

**Comment by topepo** [comment]
Closing this; more discussion can happen in `embed`. Thanks!
