### ISSUE TITLE
implementation of feature selection algorithms  (feature request)

### ISSUE THREAD

**Issue by EKtheSage** [topepo/recipes#153]
Hello,

Is there any plan to bring the caret feature selection functionality into recipes pipeline. I am looking at recursive feature elimination and genetic algorithm. Wouldn't those be part of the Step Functions - Filter?

Thanks,

Ethan

**Comment by topepo** [comment]
They won't live in `recipes` since it is pre-modeling (and not a wrapper _around_ models). The new versions of those routines will be in a new package.

**Comment by EKtheSage** [comment]
I see, thanks! I will close this issue.

**Comment by brshallo** [comment]
Curious if there are any updates on this / which package this lives in now or will live in the future?  Or if there is any documentation out on current best way to conduct this in a way consistent with `tidymodels`?  

(Code from relevant chapter in [Feature Engineering and Selection...](https://github.com/topepo/FES_Selection_Simulation/blob/master/template.R) largely uses `caret` but am curious if there were more recent materials that conducted feature selection differently.)
