### ISSUE TITLE
adding dummy variables to mark missing data before imputation

### ISSUE THREAD

**Issue by konradsemsch** [topepo/recipes#156]
It would be great to have an option in functions such as: step_meanimpute, step_modeimpute etc., that would automatically create a binary column for each imputed variables that would mark binary which values were originally imputed. Thanks to this the model could also learn from missing patters.

**Comment by topepo** [comment]
You could do that outside of the recipe and give those columns some role other than "predictor". One of the next things that is coming for recipes is to include some `dplyr` operations, including `mutate` that would allow you to do this.

**Comment by konradsemsch** [comment]
Sounds great, looking forward to the new release! When is it planned actually?
