### ISSUE TITLE
Shouldn't depend on rlang

### ISSUE THREAD

**Issue by hadley** [topepo/recipes#45]
You should import it (both in DESCRIPTION and with `@import`), otherwise it leaks in to the user's environment.  The same is probably true for dplyr too

**Comment by topepo** [comment]
Done

**Comment by topepo** [comment]
For `dplyr`, I've used that as a depends so that users can easily get the pipe operator and other `dplyr` stuff that they would probably be using.

**Comment by hadley** [comment]
As a matter of principle, I think you should selectively import and re-export just the `%>%` from magrittr.
