### ISSUE TITLE
declare output format for data matrix

### ISSUE THREAD

**Issue by topepo** [topepo/recipes#49]
Until there is a sparse tibble (I hope one day), there should be an option for `process` to convert the output to a sparse matrix format such as `Matrix::dgCMatrix`.  See `vignette("Intro2Matrix")`

**Comment by topepo** [comment]
A better option would be for `bake` and `juice` to have a `format` argument that defaults to `"tibble"` but could be `"matrix"`, `"dgCMatrix"`, or others.

**Comment by topepo** [comment]
A check for all of the same data type would need to occur for matrix and spare matrix formats. The `summary` method along with the selectors should make this easy.

**Comment by jeffwong-nflx** [comment]
Being able to output a sparse matrix would be hugely valueable! My research uses a lot of categorical variables, so I can benefit a lot from sparse matrices. Thanks!

**Comment by topepo** [comment]
@jeffwong-nflx Take a look at this and see if it fits your needs.

**Comment by jeffwong-nflx** [comment]
Thanks Max, I will take a look

**Comment by samyishak** [comment]
This feature is fantastic! Is there a way to specify that a `recipe` object outputs a sparse matrix when using `caret:::train.recipe`?

**Comment by topepo** [comment]
Unfortunately, no. I'm loath to add another argument to `trainControl`.
