### ISSUE TITLE
Documentation of feature engineering pipelines

### ISSUE THREAD

**Issue by earino** [topepo/recipes#54]
This is an incredibly interesting and exciting project. When I first saw it, one of the things that came to mind was usage of this software in regulated industries and how it could solve a whole class of problems.

Given your example:

```
sonar_rec <- recipe(Class ~ ., data = Sonar) %>%
  step_center(all_predictors()) %>%
  step_scale(all_predictors())
```

I can imagine a feature where you can say `recipe(..., document="pipeline.html")` and it would then generate a document with something like:

1. A summary of the data that was passed in (number of columns, histograms of values, etc...)
2. A documentation of the pipeline steps that were taken with the step name, parameters about how that step was configured, and examples of before and after values from a sample (or a visualization of the change.)

So like:

-----------

# Feature engineering for the Sonar dataset

The Sonar dataset has N columns and M rows. The columns are as follows:

(some table about the columns)

(visualization about the coumns)

# Feature engineering steps

## Centering predictors

A centering step was taken on columns X, Y and Z. The previous mean was blah blah and the IQR was blah blah

## Scaling Predictors

A scaling step was taken on column s blah blah blah. The previous yadda yada was etc...

-------------

I hope that makes sense?

This could then be used as a baseline document for communicating the feature engineering steps in a modeling process or production pipeline. I am eager and excited to see how this work continues!

**Comment by topepo** [comment]
It does make sense and a fair amount of this comes out in the print method. 

However, I don't think that I would include code like this in the package. They can be very sensitive to what the user wants (e.g. a tabular summary, text only, text and tables). I did something like this internally at Pfizer for `caret` and it was very difficult to maintain. 

My suggestion would be to write your own functions that would convert specific steps (and the original recipe) to markdown. This markdown can be rendered in whatever format you are interested in using. 

Note that some of the information will change as steps are processed (see the example in `summary.recipe`). This would make statements like "The previous mean was blah blah and the IQR was blah blah" difficult to do on the trained recipe object.
