### ISSUE TITLE
The most important thing missing in documentation

### ISSUE THREAD

**Issue by vzemlys** [topepo/recipes#57]
So I have the recipe. What should I do next? How to pass the recipe to `lm` for example?

**Comment by treysp** [comment]
You `process()` it to return a tibble containing the transformed data, then pass that to your estimation function (e.g., `lm()`), as described in [Basic Recipes](https://topepo.github.io/recipes/articles/Simple_Example.html). See also [the `process()` reference](https://topepo.github.io/recipes/reference/process.html).

**Comment by topepo** [comment]
> So I have the recipe. What should I do next?

@treysp is correct but it is true that pushing the data that comes out of the recipe back into a formula is a bit underwhelming. 

I'm in the process of making a recipe method for `train` and that should help a bit.

**Comment by vzemlys** [comment]
Cool. It is not clear that `process` is the last step. Especially since it is in documentation part called Preprocessing. Also `learn` is I think a bit of a misnomer, since correct me if I am wrong learning is the part where you apply the model, not the part where you preprocess data. 

Sorry for nitpicking. Hope the feedback is useful.

**Comment by topepo** [comment]
> Sorry for nitpicking. Hope the feedback is useful.

Absolutely!

>  It is not clear that `process` is the last step. Especially since it is in documentation part called Preprocessing

We're low on verbs to use 😬 . `apply` made more sense but it isn't a generic method. 

I would say that process is the last step prior to model fitting (hopefully). The "pre-" is really pre-model fitting. 

> `learn` is I think a bit of a misnomer, since correct me if I am wrong learning is the part where you apply the model, not the part where you preprocess data.

The idea is that preprocessing of the data _can_ be part of the overall modeling process and some of the steps involve estimating parameters in was that are similar to a classical model. For example, `step_other` needs to estimate the frequencies of class levels and so on. `train` was already taken by `caret` and some other packages. 

The terminology is more similar to the machine learning communities where they would need to estimate/train/learn a model such as an autoencoder prior to fitting a neural network.

**Comment by treysp** [comment]
Maybe using verbs that imply an ordering would clarify the process for people outside machine learning communities (like me). 

Although one could take it too far, what about leveraging the recipe metaphor? Maybe something like:
- First: create recipe object with `recipe()`
- Second: add steps to your recipe with `step_*()`
- Third: calculate intermediate elements such as frequencies of class levels with `prep()` (as in prepping ingredients)
- Fourth step = execute the recipe with `cook()` or something similar 

Not sure how hokey that sounds :grin:

**Comment by topepo** [comment]
`prep` is a pretty good word. Originally, I had thought of using `cook` or `serve` but we decided that we were stretching the food analogy at bit too far.

**Comment by treysp** [comment]
What about `make` for the last step? It doesn't seem as contrived as `cook`, and I doubt there would be any confusion with GNU Make.

**Comment by hadley** [comment]
I kind of like `bake()`. It rhymes with `make()` and is a bit more recipe like.
