### ISSUE TITLE
Installation failed on Windows 10 (R version 3.4.0)

### ISSUE THREAD

**Issue by Hisham-Hussein** [topepo/recipes#61]
Hello, 

I'm trying to install the package on windows 10 machine. I get the following error:

```
"D:/Program Files/R/R-3.4.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Hisham/AppData/Local/Temp/Rtmpwr9SFC/devtools13f8317d4f13/topepo-recipes-c7382d5"  \
  --library="D:/Program Files/R/R-3.4.0/library" --install-tests 

'D:\Program' is not recognized as an internal or external command,
operable program or batch file.
Installation failed: Command failed (1)
```

**Comment by topepo** [comment]
Can you provide the results of `sessionInfo()`? Do you have the `devtools` package installed? Do you have [Rtools](https://cran.r-project.org/bin/windows/Rtools/) installed?

**Comment by Hisham-Hussein** [comment]
Thanks for the reply.

About the session info:

> sessionInfo()
> R version 3.4.0 (2017-04-21)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
> [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] plyr_1.8.4          xgboost_0.6-4       randomForest_4.6-12 doSNOW_1.0.14       snow_0.4-2          iterators_1.0.8    
>  [7] e1071_1.6-8         glmnet_2.0-10       foreach_1.4.3       Matrix_1.2-9        caret_6.0-76        lattice_0.20-35    
> [13] purrr_0.2.2.2       tibble_1.3.3        tidyverse_1.1.1     ggthemes_3.4.0      lubridate_1.6.0     ggplot2_2.2.1      
> [19] tidyr_0.6.3         dplyr_0.5.0         data.table_1.10.4   readr_1.1.1        
> 
> loaded via a namespace (and not attached):
>  [1] httr_1.2.1         jsonlite_1.5       splines_3.4.0      modelr_0.1.0       assertthat_0.2.0   stats4_3.4.0      
>  [7] cellranger_1.1.0   yaml_2.1.14        backports_1.1.0    quantreg_5.33      digest_0.6.12      rvest_0.3.2       
> [13] minqa_1.2.4        colorspace_1.3-2   htmltools_0.3.6    psych_1.7.5        devtools_1.13.2    broom_0.4.2       
> [19] SparseM_1.77       haven_1.0.0        scales_0.4.1       lme4_1.1-13        MatrixModels_0.4-1 git2r_0.18.0      
> [25] mgcv_1.8-17        car_2.1-4          withr_1.0.2        nnet_7.3-12        lazyeval_0.2.0     pbkrtest_0.4-7    
> [31] mnormt_1.5-5       magrittr_1.5       readxl_1.0.0       memoise_1.1.0      evaluate_0.10      nlme_3.1-131      
> [37] MASS_7.3-47        forcats_0.2.0      xml2_1.1.1         foreign_0.8-67     class_7.3-14       tools_3.4.0       
> [43] hms_0.3            stringr_1.2.0      munsell_0.4.3      compiler_3.4.0     rlang_0.1.1        grid_3.4.0        
> [49] nloptr_1.0.4       base64enc_0.1-3    labeling_0.3       rmarkdown_1.5      gtable_0.2.0       ModelMetrics_1.1.0
> [55] codetools_0.2-15   curl_2.6           DBI_0.6-1          reshape2_1.4.2     R6_2.2.1           knitr_1.16        
> [61] rprojroot_1.2      stringi_1.1.5      parallel_3.4.0     Rcpp_0.12.11

**Comment by Hisham-Hussein** [comment]
Yes I have devtools installed, but not Rtools. I'm downloading Rtools now and will install it and get back to you.

**Comment by Hisham-Hussein** [comment]
I downloaded Rtools and installed it successfully. But when tried to install recipes, the same error popped up:

```
devtools::install_github("topepo/recipes")
Downloading GitHub repo topepo/recipes@master
from URL https://api.github.com/repos/topepo/recipes/zipball/master
Installing recipes
Installing 1 package: dplyr
also installing the dependencies ‘bindr’, ‘bindrcpp’, ‘glue’, ‘pkgconfig’, ‘plogr’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/bindr_0.1.zip'
Content type 'application/zip' length 14954 bytes (14 KB)
downloaded 14 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/bindrcpp_0.1.zip'
Content type 'application/zip' length 636504 bytes (621 KB)
downloaded 621 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/glue_1.0.0.zip'
Content type 'application/zip' length 35506 bytes (34 KB)
downloaded 34 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/pkgconfig_2.0.1.zip'
Content type 'application/zip' length 19971 bytes (19 KB)
downloaded 19 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/plogr_0.1-1.zip'
Content type 'application/zip' length 17897 bytes (17 KB)
downloaded 17 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/dplyr_0.7.0.zip'
Content type 'application/zip' length 2879560 bytes (2.7 MB)
downloaded 2.7 MB

package ‘bindr’ successfully unpacked and MD5 sums checked
package ‘bindrcpp’ successfully unpacked and MD5 sums checked
package ‘glue’ successfully unpacked and MD5 sums checked
package ‘pkgconfig’ successfully unpacked and MD5 sums checked
package ‘plogr’ successfully unpacked and MD5 sums checked
package ‘dplyr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Hisham\AppData\Local\Temp\RtmpmcYb5o\downloaded_packages
"D:/Program Files/R/R-3.4.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Hisham/AppData/Local/Temp/RtmpmcYb5o/devtools2a583849491a/topepo-recipes-c7382d5" --library="D:/Program Files/R/R-3.4.0/library"  \
  --install-tests 

'D:\Program' is not recognized as an internal or external command,
operable program or batch file.
Installation failed: Command failed (1)
```

**Comment by topepo** [comment]
[This thread](https://github.com/ramnathv/slidify/issues/247) is about the same issue for a different package. Take a look and see if that fixes it.

**Comment by Hisham-Hussein** [comment]
Thanks .. yes I did and it seemed that it solved that problem, but yet another problem emerged ! 

```
> devtools::install_github("topepo/recipes")
Downloading GitHub repo topepo/recipes@master
from URL https://api.github.com/repos/topepo/recipes/zipball/master
Installing recipes
"D:/R/R-3.4.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Hisham/AppData/Local/Temp/RtmpSKlZrF/devtools2428b436922/topepo-recipes-c7382d5" --library="D:/R/R-3.4.0/library"  \
  --install-tests 

* installing *source* package 'recipes' ...
** R
** data
*** moving datasets to lazyload DB
** tests
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'dimRed' 0.0.3 is being loaded, but >= 0.1.0 is required
ERROR: lazy loading failed for package 'recipes'
* removing 'D:/R/R-3.4.0/library/recipes'
Installation failed: Command failed (1)
```

**Comment by topepo** [comment]
You should reinstall that package (from the [current version on CRAN](https://cran.r-project.org/web/packages/dimRed/index.html) version). 

Also, check `.libPaths()` to see if you have more than one place where packages are installed. There are sometimes conflicts when they are installed to a different path than expected. 

Also also, make sure other instances of R are closed when installing. R doesn't give very informative errors (or any feedback) about installation issues when this occurs.

**Comment by Hisham-Hussein** [comment]
Finally It worked .. thanks a lot! 

And great package by the way .. I watched your recent rstudio webinar, and can't wait to use it. It would be great if you added some detailed vignettes, apart from the webinar. 

By the way, have you tried the package [vtreat](https://cran.r-project.org/web/packages/vtreat/index.html)? for automating some transformation and preprocessing steps? 

I would like to hear your feedback about this package as well.

Thanks again

**Comment by topepo** [comment]
> can't wait to use it

Thanks. Keep in mind though that there will probably be some smallish [syntax changes](https://github.com/topepo/recipes/issues/59) that will occur before it gets to CRAN. I'm hoping to submit it in a month. 
 

> It would be great if you added some detailed vignettes, apart from the webinar.

[I agree](https://topepo.github.io/recipes/) =]

> By the way, have you tried the package vtreat? for automating some transformation and preprocessing steps?

I have read about it but not used it. It does more supervised things than recipes so there are slightly different directions.

**Comment by Hisham-Hussein** [comment]
Oh .. thanks a lot for the vignettes .. that's great

**Comment by Hisham-Hussein** [comment]
I'll go ahead and close this issue since it's solved ... thanks again!

**Comment by kriksh** [comment]
Hello,

I'm Trying to install R 3.4.3 on windows 10 through SCCM(system context)
, while installing it I'm getting " Internal error: Failed to expandshell folder constant "userdocs" 
any answers please let me know thanks!
