### ISSUE TITLE
step_intercept?

### ISSUE THREAD

**Issue by alexpghayes** [topepo/recipes#62]
Thanks for this wonderful package! I'm currently using recipes to strip out some troublesome factor levels with `step_other` before passing a design matrix to `glm.fit`, and the package is making my life much better.

I was a little surprised that

```
data(okc)

okc %>% 
  recipe(age ~ height) %>% 
  step_center(height) %>% 
  prepare(okc) %>% 
  bake(okc)  
```

doesn't add an intercept column like I'd get if I just used `glm`. Are there plans for something like `step_intercept`, or is there an assumption that I should `cbind` on an intercept column outside of the recipe interface?

**Comment by topepo** [comment]
I had not thought of that. Would you like to write one and submit a PR?

**Comment by alexpghayes** [comment]
Sure. I'll try to find time before the end of the weekend. I'll include some changes to the documentation so nobody else gets surprised.
