### ISSUE TITLE
compile process to SQL

### ISSUE THREAD

**Issue by rgayler** [topepo/recipes#73]
Would it be possible/useful to have an option for process() such that it compiles the recipe to SQL and executes it on a DB (like https://github.com/wwbrannon/sqlscore/ or dbplyr). This might be useful for people who want to preprocess data on a DB that is too big to fit in RAM.

learn() could still be run on a sample in RAM (and some of the functions in learn would be impossible to implement in SQL).

**Comment by topepo** [comment]
Something like this is in the long term plans for recipes (with other backends too). It is certainly possible and there would be limitations of course; I don't see sql doing a nearest neighbor imputation anytime soon. 

After I get the initial version on CRAN (I think by the end of this month), other computational engines/backends will be one of the next features that we will get into.
