### ISSUE TITLE
Error in yj_trans when data contain NA values

### ISSUE THREAD

**Issue by pgarnry** [topepo/recipes#90]
Since the latest caret update as of 2017-09-07 when the Yeo-Johnson transformation code was updated...

_The Yeo-Johnson transformation parameter estimation code was rewritten and not longer requires the car package_

The old code supported na.rm across all preProcess methods, but the updated code for Yeo-Johnson does not, as the function nn_trans only subsets positive values and assumes no NA values in the input data. The na.rm method should easily be implemented in the yj_trans function as a hot fix aligning it with the preProcess methods such as center, scale etc.

Thanks and really appreciate your work with caret/recipes etc.

**Comment by topepo** [comment]
Got it. Thanks
