### ISSUE TITLE
Is it possible to return a sparse matrix?

### ISSUE THREAD

**Issue by jeffwong-nflx** [topepo/recipes#93]
To me recipes is such a great idea because it is like the grammar of feature engineering. Like model.matrix and sparse.model.matrix, is there any way for `recipe` to return a sparse matrix instead of a tbl? This is especially useful in the case of many `step_dummy`, or `step_interact` with `step_dummy`

**Comment by topepo** [comment]
Not yet but see [issue #49](https://github.com/topepo/recipes/issues/49). I'll close this and you can look for progress there.
