### ISSUE TITLE
New Function: train_test_split

### ISSUE THREAD

**Issue by mdancho84** [topepo/recipes#99]
Feature Request: New function to efficiently split data into training, test and validations sets. 

This is a super common action, and recipes seems like a good package for it:
- python / sklearn.model_selection has `train_test_split()`
- H2O for R has `h2o.splitFrame()` (I love this function, but is for H2OFrame objects, not tidy df's)

Here's a potential version called `train_test_split()` that I'm using currently in the tidyverse. Still needs some work for handling errors and incorrect inputs. You might be able to use it as a start. The important thing is to drive the split by the `ratios` argument (same as `h2o.splitFrame()`). One ratio splits into train and test. Two ratios splits into train, test, and validation sets. 

``` r
train_test_split <- function(data, ratios = 0.7, seed = NULL) {
  
  # Checks
  if (sum(ratios) > 1) stop("`ratios` must be less than 1")
  if (sum(ratios) < 0) stop("`ratios` must be greater than 0")
  if (length(ratios) > 2 || length(ratios) < 0) stop("`ratios` must be one or two in length")
  if (!is.numeric(ratios)) stop("`ratios` must be numeric")
  
  n_row <- nrow(data)
  
  # Create splitting specification
  if (length(ratios) == 1) {
      spec <- c(train = ratios[[1]], test = 1 - sum(ratios))
  } else if(length(ratios) == 2) {
    spec <- c(train = ratios[[1]], test = ratios[[2]], valid = 1 - sum(ratios))
  } else {
    stop("`ratios` must be length 1 or 2")
  }
  
  # Create splitter
  if(!is.null(seed)) set.seed(seed)
  splitter <- sample(cut(seq(n_row), n_row * cumsum(c(0, spec)), labels = names(spec)))
  
  # Split using splitter
  ret <- split(data, splitter)
  
  return(ret)
  
}

train_test_split(mtcars, ratios = c(0.7, 0.15), seed = 100)
#> $train
#>                      mpg cyl  disp  hp drat    wt  qsec vs am gear carb
#> Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
#> Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
#> Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
#> Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
#> Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
#> Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
#> Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
#> Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
#> Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
#> Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
#> Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
#> Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
#> Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
#> Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
#> AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
#> Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
#> Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
#> Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
#> Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
#> Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8
#> Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2
#> 
#> $test
#>                     mpg cyl  disp  hp drat    wt  qsec vs am gear carb
#> Merc 230           22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
#> Merc 280C          17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
#> Cadillac Fleetwood 10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
#> Chrysler Imperial  14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
#> Lotus Europa       30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
#> 
#> $valid
#>              mpg cyl  disp  hp drat    wt  qsec vs am gear carb
#> Valiant     18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
#> Merc 240D   24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
#> Merc 450SLC 15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
#> Camaro Z28  13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
#> Fiat X1-9   27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
```

**Comment by topepo** [comment]
I've avoided adding steps that or modify the rows of the data set (such as splitting, down- or up-sampling, etc). The main reason is that steps are designed to do the same thing to a data set used in `bake` as it does for the data in `prep`. The type of operation that you are interested in should happen outside of the recipes. 

`rsample` has a function called [`initial_split`](https://topepo.github.io/rsample/reference/initial_split.html) that does what you are interested in.

**Comment by mdancho84** [comment]
Was not aware `rsample` existed. Thanks for the heads up. The `initial_split` function looks like it does the trick, albeit in a slightly different way. These are really great packages and I appreciate your effort and hard work. Especially with making the normal ML preprocessing tasks much easier!

Out of curiosity, are there any plans for a tutorial to show off the workflow for a typical ML problem from start to finish, similar to Hadley's work on R4DS? This is my struggle, knowing what tools you have in your packages and where I can use 'em. Now that I know about `rsample` it seems like k-fold cross validation may be easier. Again, realize you have a lot going on. Just curious on how to use your tools.

**Comment by topepo** [comment]
I'm doing a tutorial at the Rstudio conference in late January and that will be about half of the session. That class is full but there should be another sometime next year and the conference video and notes will be posted. 

I'll probably write another book on just that once I've gotten most of the pieces nailed down. I think I have about half of the basic infrastructure worked out.

**Comment by mdancho84** [comment]
Very cool. I unfortunately won't be at the event (baby on the way), but our software manager, Davis Vaughan (@dvaughan), will be speaking on future of time series in the tidyverse. I'll certainly be checking your videos out once released.

The book will be very useful. It's a great way to speed up adoption of these packages. Looking forward to seeing what you put out. These packages will most likely be worked into my ML workflow. Keep your eyes peeled for a blog using `keras` shortly. I'll be using `recipes` for the preprocessing.

**Comment by topepo** [comment]
> Keep your eyes peeled for a blog using `keras` shortly.

Absolutely. I'd like to see that.

**Comment by mdancho84** [comment]
Hey Max, here's the article:
http://www.business-science.io/business/2017/11/28/customer_churn_analysis_keras.html

Let me know what you think... Thanks for the great work on `rsample`, `recipes`, and `yardstick`!
